### ISSUE TITLE
UserDialog onShow

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-web#427]
Why are we using `onShow` in UserDialog instead of `init`?

**Comment by Abyss777** [comment]
Because we use `record.id` https://github.com/tananaev/traccar-web/blob/master/web/app/view/UserDialogController.js#L29

`record` loaded after initialization but before show  https://github.com/tananaev/traccar-web/blob/master/web/app/view/SettingsMenuController.js#L65

**Comment by tananaev** [comment]
OK, I understand why it's there. Is it for manager user? Can't we just keep those field for manager?

Another thing I noticed looking through the code is that we disable some fields and hide others. For example "readonly" and "device readonly". Is there any reason for that? I'm thinking that we should make it more consistent.

**Comment by Abyss777** [comment]
These fields disabled/hided for "Account" dialog and we "unhide"/enable them for admin and manager.
Also, we leave them disabled if manager edit himself through "Users" dialog. 

> Can't we just keep those field for manager?
Did not catch the idea, please clarify.

About hiding and disabling..., as I remember, at the beginning You hided some fields for ordinary users because dialog was too long. Now, after grouping it is not necessary, and we can just disable them for consistence.

**Comment by tananaev** [comment]
We can allow manager to edit those fields for his own account. That way the logic is simpler.

I agree about disabling fields for consistency.

**Comment by Abyss777** [comment]
We can't do that, it is not allowed in backend. Also it worked for ordinary user "Account" dialog.
Or do you mean just allow users get errors if they edited something forbidden?

**Comment by tananaev** [comment]
Another option is to pass some special flag when we open the dialog from settings menu, not from user list.

**Comment by Abyss777** [comment]
Yes, I'll consider how to pass parameter in a good way. May be through constructor.

**Comment by tananaev** [comment]
You can just pass it as a member variable when you create a window.

**Comment by Abyss777** [comment]
Closing this, fixed by #432
