### ISSUE TITLE
feature rqst : set max zoom level

### ISSUE THREAD

**Issue by flyjodel** [tananaev/traccar-web#521]
Hi,

I'm using traccar this year to follow a competition where the pilots don't know where they have to fly before takeoff. But as they take off in a row and not all together, the live-tracking could give the next ones some advice about the track to follow.

So as far as I can imagine, is it possible to : 
- disable any zooming above a certain value in order to limit the vieable area to a limited detailed map ?
- or... maybe, but it's more difficult... put some adjustable delay to the tracks, so that the actual position is not displayed, but will be desplayed with a delay of 10 minutes, or one/two hours ?

Thanks
Michel

**Comment by tananaev** [comment]
I guess you meant minimum zoom level.

Both options should work. Which one to choose probably depends on your business requirements.

**Comment by flyjodel** [comment]
in fact as far as I understand, zoom = 16 is narrow, and zoom = 1 is almost the whole planet. So if this assessment is valid, then I would like limit the possibility to zoom =1 - 8 for example and prevent from zooming more in , as zoom = 9 - 16

**Comment by tananaev** [comment]
I don't understand how that would solve your original problem.

**Comment by flyjodel** [comment]
the people could not zoom into the map to know the exact position of the turning points. They would be limited to a big map, with not enough details to cheat.

**Comment by tananaev** [comment]
OK, but what's the point on the map then?

**Comment by flyjodel** [comment]
the point is that at present, it is possible to zoom until zoom=16. But i would like that the maximum number for the zoom level achievable with the mouse is zoom = 8 for example

**Comment by 9662** [comment]
@tananaev 

> OK, but what's the point on the map then?

This appears to be a [gliding competition](http://www.soaringspot.com/), where sailplane pilots have to fly to within a certain radius of a series of “turning points” before proceeding to the next. Since they have no engines, in order to do that they must trade altitude for speed (i.e., glide), and in order to gain altitude they must find ascending currents of air (thermal, orographic, etc.), which is 90% of the skill of a sailplane pilot.

If you have a map which is too detailed, competitors taking off latter can cheat by looking up their rivals' tracks on the map¹ and identify, e.g., that on this crop field next to that factory there is a strong thermal. This problem can be minimised if, as @flyjodel says, you limit the resolution of the map to within a nautical mile or two, which is wider than most thermals useful to gliders.

Of course, the map is still a useful tool both for the organisation to track competitors (perhaps at max zoom level) and for the public (on the ground at the departure airfield or over the internet) to follow the progress of the competition.

This is actually an instance of this user story: https://github.com/tananaev/traccar/issues/3489 

Hope this provides some clarification.

¹ This is akin to a ski tourer following the tracks of a preceding skier: it relieves you from having to do your own pathfinding. And as in skiing, if the guy before you got it wrong and ended up in a crevasse, so do you. 😈

**Comment by tananaev** [comment]
I guess that kind of makes sense. It should be fairly easy to add zoom limit.

**Comment by flyjodel** [comment]
@9662 : you're right, we could compare it to a gliding competition, but it's with motor planes. The track the pilots have to fly is only revealed 15 minutes before take off, but as they takeoff in a 5 or 3 minutes pace, a pilot going last in queue would have a big advantage on the first ones if he knew what the turning point are in advance.

So, as I would like to publish the map so that the family and supporters can watch the competition live, I would like to limit the maximum zoom level to a certain value, prohibiting from getting the coordinates of the turning points via the website.

The other way could be publishing an own rastermap, but generating the tiles and putting a tiles server is out of my knowledge range.

Thank you
